// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a testimonial for the gym if one is missing.
 *
 * - generateTestimonial - A function that handles the testimonial generation process.
 * - GenerateTestimonialInput - The input type for the generateTestimonial function.
 * - GenerateTestimonialOutput - The return type for the generateTestimonial function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTestimonialInputSchema = z.object({
  gymName: z.string().describe('The name of the gym.'),
  serviceDescription: z.string().describe('A description of the gym and its services.'),
});
export type GenerateTestimonialInput = z.infer<typeof GenerateTestimonialInputSchema>;

const GenerateTestimonialOutputSchema = z.object({
  testimonial: z.string().describe('A generated testimonial for the gym.'),
});
export type GenerateTestimonialOutput = z.infer<typeof GenerateTestimonialOutputSchema>;

export async function generateTestimonial(input: GenerateTestimonialInput): Promise<GenerateTestimonialOutput> {
  return generateTestimonialFlow(input);
}

const generateTestimonialPrompt = ai.definePrompt({
  name: 'generateTestimonialPrompt',
  input: {schema: GenerateTestimonialInputSchema},
  output: {schema: GenerateTestimonialOutputSchema},
  prompt: `You are a marketing expert specializing in writing compelling testimonials.

  Generate a testimonial for {{gymName}} based on the following description of the gym and its services:
  {{serviceDescription}}

  The testimonial should be positive and highlight the benefits of joining the gym.
  The testimonial should sound authentic and be approximately 2-3 sentences long.`,
});

const generateTestimonialFlow = ai.defineFlow(
  {
    name: 'generateTestimonialFlow',
    inputSchema: GenerateTestimonialInputSchema,
    outputSchema: GenerateTestimonialOutputSchema,
  },
  async input => {
    const {output} = await generateTestimonialPrompt(input);
    return output!;
  }
);
